package view.dialog;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class SingupDialogController {
	@FXML
	private Label txtPopupName;

	// Event Listener on Button.onAction
	@FXML
	public void goToHome(ActionEvent event) {
		// TODO Autogenerated
	}
}
