package view.login;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.layout.Pane;
import view.ViewManagement;

import java.io.IOException;

import javafx.event.ActionEvent;

public class LoginGraphic {
	
	private static ViewManagement viewM;

	// Event Listener on Button.onAction
	@FXML
	public void loginPress(ActionEvent event) {
		try {
			Pane pane = (Pane) FXMLLoader.load(getClass().getResource("home/Home.fxml"));
			viewM.changeScene(pane);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void singupPage(ActionEvent event) {
		// TODO Autogenerated
	}
}
