package view.add;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ScrollPane;

public class AddController {
	@FXML
	private Button btnUser;
	@FXML
	private Button btnHome;
	@FXML
	private Button btnBrand;
	@FXML
	private Button btnAddDress;
	@FXML
	private Button btnFavorite;
	@FXML
	private Button btnOutfits;
	@FXML
	private Button btnSize;
	@FXML
	private Button btnCategory;
	@FXML
	private Button btnGoBack;
	@FXML
	private Button btnGoAhead;
	@FXML
	private ScrollPane scrollPnl;

	// Event Listener on Button[#btnUser].onAction
	@FXML
	public void goUser(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnHome].onAction
	@FXML
	public void goHome(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBrand].onAction
	@FXML
	public void goBrand(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAddDress].onAction
	@FXML
	public void goAddDress(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnFavorite].onAction
	@FXML
	public void goFavorite(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnOutfits].onAction
	@FXML
	public void goOutfits(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSize].onAction
	@FXML
	public void goSize(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCategory].onAction
	@FXML
	public void goCategory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnGoBack].onAction
	@FXML
	public void goBack(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnGoAhead].onAction
	@FXML
	public void goAhead(ActionEvent event) {
		// TODO Autogenerated
	}
}
